/**
 * ASCII portrait of Andre, rendered from the studio headshot.
 *
 * Generated by sampling per-character luminance cells, then blending two
 * layers: a global tone stretch (lo 0.20 → hi 0.82) that keeps hair and blazer
 * reading as solid dark mass, and a locally-normalised layer (radius 5 cells,
 * gain 0.30, centred at 0.74) that is gated to mid tones so the face — brows,
 * eyes, nose, mouth — actually resolves. Skin only spans ~0.09 of luminance,
 * so without that second layer the face renders as an empty oval.
 *
 * Ramp " .:-=+*#%@" is inverted: the pure-white backdrop keys out to spaces and
 * the subject is what gets drawn. Cell aspect 0.60 assumes JetBrains Mono at
 * line-height 1 — both render sites set that, so keep them in sync.
 *
 * This is the only portrait of Andre in the site; there is no photograph.
 */
export const ASCII_PORTRAIT: string[] = [
  "                      =###%###%#%%##*.",
  "                   .*#%%%%%%%%%%%%%%###=",
  "                 +%%%%%@%%%@%%%%%%%%%%##*",
  "               =%%%@@@@@@@@@@@%%%%%%%%%###",
  "              #%%%%@@@@@%%%%%%%%%%%%%%%%%#*",
  "             %%%%%%%%%#*+=::++=++*##%%%%%%#*",
  "            %%%%%%#+-:... .........:=*#%%%##.",
  "           #%%%%%#:..               ...#%%%%*",
  "           %%%%%%*..        .          =#%%%#",
  "          *%%%%%#-   ................  .#%%%%#",
  "          .%%%%#*................ ......=#%%#-",
  "           #%##*..:::-=+=.      .-==-:::.=##*",
  "           +%#*:.:-::-==+==:  .=+*+==---:.*#",
  "            ##+.....:-*#*-.   .:.:+=-:::..=*",
  "            -*+....-+**+=+:.  :-:-**++-...-+.",
  "             -=::....  :::-:.:-=-.:......::-.",
  "           .::-::.       .:-:::--:.     .::-.",
  "           .-:--::.      .:     :::.    :::-",
  "            ::=--::     .: :   = ::    :----",
  "             :-=--:.    .:-::.:--.    .:--:",
  "               :---:.  ..::::::::::. .:--.",
  "                ---:::.:=+**++*#*+=::.:--",
  "                 =--:..:+++-:::=*+-:.::-",
  "                 .=--::. .:---==-::::--",
  "                  ===-:..      ...::---",
  "                  :-===:.        .-==-:",
  "                  ::-=+**==-====+*++-::",
  "                  :..:-+***++++++*=-:...",
  "                -*....::----=====--:....%.",
  "              -#@#..  ..:::::::::::.. ..%%%#*=",
  "           +%@@@@@:.        .......   .=@@@@@@@@@%*",
  "        *%@@@@@@@@*..          ...    -%@@@@@@@@@@@@%%#:",
  "    +%@@@@@@@@@@@@@-..    .......   .=%@@@@@@@@@@@@@@@@%",
  "+%%@@@@@@@@@@@@@@@@%*-..          .:#@@@@@@@@@@@@@@@@@@@",
  "@@@@@@@@@@@@@@@@@@@@%%#+-::.....:=*%@@@@@@@@@@@@@@@@@@@@",
];

/** Grid size — used to size the monospace boxes that hold the portrait. */
export const ASCII_COLS = 56;

/** Cell aspect the art was rendered for: char advance ÷ line-height. */
export const ASCII_LINE_HEIGHT = 1;
