export const personal = {
  name: "Andre Milan A. Arañas",
  shortName: "Andre",
  title: "BS Computer Science",
  subtitle: "Web Developer Intern · eComia",
  email: "aaaranas@up.edu.ph",
  phone: "+639287056564",
  github: "github.com/aaaranas",
  githubUrl: "https://github.com/aaaranas",
  location: "Cebu City, Philippines",
  bio: "Third-year BS Computer Science student at UP Cebu, currently interning as a Web Developer at eComia. I build things for the web — primarily owning frontend architecture with React and Next.js, while shipping full-stack features end-to-end.",
  portfolioUrl: "https://andre-milan-aranas.vercel.app/",
};

export const projects = [
  {
    id: "donezo",
    name: "Donezo",
    emoji: "✅",
    tagline: "Offline-first Kanban with real-time cross-device sync",
    description:
      "Personal Kanban app with offline support and real-time cross-device sync via WebSockets. Implemented last-write-wins conflict resolution. Drag-and-drop columns, tag system with auto-coloring, due date display. Backend includes JWT auth, cron-based soft-delete cleanup, and a WebSocket sync layer.",
    stack: ["HTML", "CSS", "JavaScript", "Node.js", "Express.js", "PostgreSQL"],
    role: "Full Stack",
    highlight: "WebSocket sync",
    color: "#4fffbf",
    github: "https://github.com/aaaranas",
    live: "",
  },
  {
    id: "sanbidet",
    name: "San Bidet Cebu",
    emoji: "🚽",
    tagline: "Crowdsourced bidet-rating platform for Cebu restrooms",
    description:
      "Built a crowdsourced platform for rating bidet availability in Cebu restrooms. Public-facing listing interface and a separate admin dashboard for managing submissions and ratings. Sole full-stack developer from UI to database.",
    stack: ["Flutter", "PostgreSQL", "Vercel"],
    role: "Sole Full Stack",
    highlight: "Solo project",
    color: "#ffdf5f",
    github: "https://github.com/aaaranas",
    live: "https://san-bidet-cebu-admin.vercel.app/",
  },
  {
    id: "scheduling",
    name: "Sorting Algorithm Calculator",
    emoji: "⚙️",
    tagline: "Interactive OS scheduling algorithm visualizer",
    description:
      "Interactive calculator supporting FCFS, SJF (Non-preemptive), SJF (Preemptive), Priority, and Round Robin. Users add processes with custom burst times, run calculations, and compare algorithm behavior. Designed as a study tool; deployed publicly for student use. Fully responsive.",
    stack: ["HTML", "JavaScript", "CSS", "Vercel"],
    role: "Solo Dev",
    highlight: "Public tool",
    color: "#ff8f6f",
    github: "https://github.com/aaaranas",
    live: "https://cpu-schedule-calculator.vercel.app/",
  },
  {
    id: "heartbeat",
    name: "Heartbeat Flower Shop",
    emoji: "🌸",
    tagline: "E-commerce frontend with cart & checkout flow",
    description:
      "Frontend for a flower shop e-commerce site featuring product browsing, search and filter, shopping cart, and full checkout flow. Focused on component architecture, layout responsiveness, and UX using Next.js and Tailwind CSS.",
    stack: ["JavaScript", "React", "Next.js", "Tailwind CSS", "Vercel"],
    role: "Frontend Dev",
    highlight: "E-commerce UX",
    color: "#ff6faf",
    github: "https://github.com/aaaranas",
    live: "https://heartbeat-flower-shop.vercel.app/",
  },
  {
    id: "tacfinity",
    name: "Tacfinity",
    emoji: "🎮",
    tagline: "Multiplayer Tic Tac Toe with ELO ranking",
    description:
      "Online multiplayer Tic Tac Toe with private room codes, live WebSocket sync, and an offline AI opponent. Handled frontend UI and contributed to backend logic including an ELO-based ranking system and player stats. Used Prisma ORM; learned real-time state management across connected clients.",
    stack: ["TypeScript", "React", "Vite", "Tailwind CSS", "Express.js", "Socket.io", "PostgreSQL", "Prisma"],
    role: "Full Stack",
    highlight: "ELO + WebSockets",
    color: "#bf6fff",
    github: "https://github.com/aaaranas",
    live: "https://tacfinity-web.vercel.app/",
  },
  {
    id: "irregskolar",
    name: "IrregSkolar",
    emoji: "🎓",
    tagline: "Academic schedule planner for irregular students",
    description:
      "Web app that helps irregular students plan and visualize their course load each semester. Handles conflict detection, unit load computation, and schedule grid visualization. Built to ease the manual burden of enrollment planning at UP.",
    stack: ["TypeScript", "React", "Next.js", "Tailwind CSS", "Vercel"],
    role: "Solo Dev",
    highlight: "Student tool",
    color: "#5fb3ff",
    github: "https://github.com/aaaranas",
    live: "https://irregskolar.vercel.app/",
  },
  {
    id: "7gb-construction",
    name: "7GB Construction",
    emoji: "🏗️",
    tagline: "Company website for a construction services firm",
    description:
      "Professional company website for 7GB Construction Services, featuring project showcases, service listings, and a contact section. Built for a real client with a focus on clean design, fast load times, and mobile responsiveness.",
    stack: ["React", "Next.js", "Tailwind CSS", "Vercel"],
    role: "Sole Developer",
    highlight: "Client project",
    color: "#ffb347",
    github: "https://github.com/aaaranas",
    live: "https://7gb-construction-services.vercel.app/",
  },
  {
    id: "myle-photography",
    name: "Myle Photography",
    emoji: "📷",
    tagline: "Photography portfolio & booking site",
    description:
      "Portfolio and booking website for a photographer client. Features a masonry gallery, service packages, and a contact/booking form. Designed to showcase the photographer's style with a minimal, image-forward layout.",
    stack: ["React", "Next.js", "Tailwind CSS", "Vercel"],
    role: "Sole Developer",
    highlight: "Client project",
    color: "#c8a97e",
    github: "https://github.com/aaaranas",
    live: "https://myle-photography.vercel.app/",
  },
];

export const skills = {
  Frontend: [
    "React",
    "Next.js",
    "TypeScript",
    "JavaScript",
    "Tailwind CSS",
    "HTML",
    "CSS",
    "Responsive Design",
    "Socket.io Client",
    "Flutter",
  ],
  "Backend & APIs": [
    "Node.js",
    "Express.js",
    "PostgreSQL",
    "Firebase",
    "Firestore",
    "Supabase",
    "tRPC",
    "Socket.io Server",
    "Prisma ORM",
  ],
  Tools: ["Git", "GitHub", "GitLab", "Vercel", "JetAdmin", "Docker", "Postman"],
};

export const experience = [
  {
    company: "eComia",
    role: "Web Developer Intern",
    period: "2026 · Present",
    type: "internship",
    highlights: [
      "Acting as Project Manager & Frontend Developer across projects — owning both coordination and hands-on implementation",
      "Built the Event QR Admission system end-to-end: full-screen kiosk display (React + Vite) reacting to real-time Firestore writes with celebratory animated reveals",
      "Managed a multi-platform system: web display, Flutter mobile QR scanner, and JetAdmin admin panel — all wired to the same Firebase/Firestore project",
      "Collaborating on React/Next.js e-commerce systems in a professional team environment",
    ],
    project: {
      name: "Event QR Admission",
      stack: ["React", "Vite", "Tailwind CSS", "Firebase", "Firestore", "Flutter", "JetAdmin"],
      description: "Full-screen guest check-in kiosk. Role: Project Manager & Frontend Developer (Web + Mobile). QR scanned → Firestore write → celebratory animated reveal in under 20ms.",
    },
  },
];

export const education = [
  {
    school: "University of the Philippines Cebu",
    degree: "Bachelor of Science in Computer Science",
    period: "Expected: Jul 2027",
    courses: [
      "Data Structures & Algorithms",
      "Operating Systems",
      "Database Systems",
      "Software Engineering",
      "Computer Networks",
    ],
  },
  {
    school: "Philippine Science High School — Central Visayas Campus",
    degree: "Science, Technology, Engineering & Mathematics",
    period: "Graduated: May 2021",
    courses: ["With High Honors"],
  },
];
