export const personal = {
  name: "Andre Milan A. Arañas",
  shortName: "Andre",
  title: "BS Computer Science",
  subtitle: "Web Developer Intern · eComia",
  email: "aaaranas@up.edu.ph",
  phone: "+639287056564",
  github: "github.com/aaaranas",
  githubUrl: "https://github.com/aaaranas",
  location: "Cebu City, Philippines",
  bio: "I build fast, accessible web apps that solve real problems. Currently shipping production features at eComia as a Web Developer Intern — from a Cebu-wide transit planner used by local commuters to a real-time event check-in kiosk. Third-year CS at UP Cebu, frontend-leaning and full-stack capable.",
  portfolioUrl: "https://andre-milan-aranas.vercel.app/",
};

export const projects = [
  {
    id: "komyut-ta-bai",
    name: "Komyut ta Bai",
    emoji: "🚌",
    tagline: "The transit planner Cebu never had — Google Maps won't cover this",
    description:
      "Google Maps has no transit data for most of Cebu. I built the alternative: a province-wide multimodal planner covering buses, v-hires, jeepneys, and island ferries (Bantayan, Camotes). Enter an origin and destination; get multi-leg journey plans with transfer points, fares, and travel times. Fully offline after first load as a PWA — critical for riders with spotty data. Routing is Dijkstra on an in-memory transit graph with ~60 jeepney routes. Built solo; still actively expanding coverage.",
    stack: ["Next.js", "TypeScript", "Tailwind CSS", "MapLibre GL", "OpenStreetMap", "Serwist", "Vercel"],
    role: "Solo Dev",
    highlight: "WIP · Civic Tech",
    color: "#34d399",
    github: "https://github.com/aaaranas/komyut-ta-bai",
    live: "https://komyut-ta-bai-cebu.vercel.app/",
  },
  {
    id: "donezo",
    name: "Donezo",
    emoji: "✅",
    tagline: "Offline-first Kanban that syncs the moment you reconnect",
    description:
      "My first time shipping a WebSocket-powered sync system end-to-end. Tasks update across all open devices in real-time; go offline and they queue — reconnect and they reconcile via last-write-wins conflict resolution. Built JWT auth, drag-and-drop columns, tag auto-coloring, due date display, and cron-based soft-delete cleanup from scratch. The WebSocket layer was the hardest part and the most rewarding to get right.",
    stack: ["HTML", "CSS", "JavaScript", "Node.js", "Express.js", "PostgreSQL"],
    role: "Full Stack",
    highlight: "WebSocket sync",
    color: "#4fffbf",
    github: "https://github.com/aaaranas",
    live: "",
  },
  {
    id: "sanbidet",
    name: "San Bidet Cebu",
    emoji: "🚽",
    tagline: "Crowdsourced map of bidet availability across Cebu",
    description:
      "A problem-first project: finding a clean restroom with a bidet in Cebu is harder than it should be. Built a crowdsourced platform where locals submit and rate bidet availability — public listing interface plus a separate admin dashboard for managing submissions. Sole full-stack developer, from schema design to deployment. First project where I owned both the frontend UX and the database layer.",
    stack: ["Flutter", "PostgreSQL", "Vercel"],
    role: "Sole Full Stack",
    highlight: "Solo project",
    color: "#ffdf5f",
    github: "https://github.com/aaaranas",
    live: "https://san-bidet-cebu-admin.vercel.app/",
  },
  {
    id: "scheduling",
    name: "Sorting Algorithm Calculator",
    emoji: "⚙️",
    tagline: "Study tool for OS scheduling algorithms — used by classmates",
    description:
      "Built this to stop re-doing scheduling calculations by hand for OS class. Supports FCFS, SJF (preemptive and non-preemptive), Priority, and Round Robin — add processes with custom burst times and see Gantt charts with waiting/turnaround times. Shared it with classmates and it spread; ended up being used for exam review by people I'd never met. First time I shipped something people actually came back to.",
    stack: ["HTML", "JavaScript", "CSS", "Vercel"],
    role: "Solo Dev",
    highlight: "Public tool",
    color: "#ff8f6f",
    github: "https://github.com/aaaranas",
    live: "https://cpu-schedule-calculator.vercel.app/",
  },
  {
    id: "heartbeat",
    name: "Heartbeat Flower Shop",
    emoji: "🌸",
    tagline: "E-commerce UI with search, cart, and full checkout flow",
    description:
      "Full e-commerce frontend — product browsing with search and filter, shopping cart with persistent state, and a multi-step checkout flow. This was my deep-dive into component architecture and state management in React: how to structure a real feature tree, handle shared cart state, and keep the UI responsive across breakpoints. Clean, fast, and mobile-first.",
    stack: ["JavaScript", "React", "Next.js", "Tailwind CSS", "Vercel"],
    role: "Frontend Dev",
    highlight: "E-commerce UX",
    color: "#ff6faf",
    github: "https://github.com/aaaranas",
    live: "https://heartbeat-flower-shop.vercel.app/",
  },
  {
    id: "tacfinity",
    name: "Tacfinity",
    emoji: "🎮",
    tagline: "Multiplayer Tic Tac Toe with live rooms and ELO ranking",
    description:
      "Took a classic game seriously: private room codes, live WebSocket sync, an offline AI opponent, and a real ELO ranking system with persistent player stats. Handled the full frontend and contributed to backend architecture — this is where I learned how real-time state across multiple connected clients actually works. Used Prisma ORM for the first time; the ELO math and concurrent session handling were the interesting parts.",
    stack: ["TypeScript", "React", "Vite", "Tailwind CSS", "Express.js", "Socket.io", "PostgreSQL", "Prisma"],
    role: "Full Stack",
    highlight: "ELO + WebSockets",
    color: "#bf6fff",
    github: "https://github.com/aaaranas",
    live: "https://tacfinity-web.vercel.app/",
  },
  {
    id: "irregskolar",
    name: "IrregSkolar",
    emoji: "🎓",
    tagline: "Schedule planner for irregular UP students — built for myself first",
    description:
      "Enrollment at UP as an irregular student means manually juggling prerequisites, time conflicts, and unit caps across a spreadsheet. I built the tool I needed: pick your courses, get conflict detection, unit load computation, and a visual schedule grid instantly. Shared it with org-mates; turned into something classmates actually use during enlistment season. Feels good to solve a real problem for real people I know.",
    stack: ["TypeScript", "React", "Next.js", "Tailwind CSS", "Vercel"],
    role: "Solo Dev",
    highlight: "Student tool",
    color: "#5fb3ff",
    github: "https://github.com/aaaranas",
    live: "https://irregskolar.vercel.app/",
  },
  {
    id: "7gb-construction",
    name: "7GB Construction",
    emoji: "🏗️",
    tagline: "Company website for a construction services firm",
    description:
      "Professional company website for 7GB Construction Services, featuring project showcases, service listings, and a contact section. Built for a real client with a focus on clean design, fast load times, and mobile responsiveness.",
    stack: ["React", "Next.js", "Tailwind CSS", "Vercel"],
    role: "Sole Developer",
    highlight: "Client project",
    color: "#ffb347",
    github: "https://github.com/aaaranas",
    live: "https://7gb-construction-services.vercel.app/",
  },
  {
    id: "myle-photography",
    name: "Myle Photography",
    emoji: "📷",
    tagline: "Photography portfolio & booking site",
    description:
      "Portfolio and booking website for a photographer client. Features a masonry gallery, service packages, and a contact/booking form. Designed to showcase the photographer's style with a minimal, image-forward layout.",
    stack: ["React", "Next.js", "Tailwind CSS", "Vercel"],
    role: "Sole Developer",
    highlight: "Client project",
    color: "#c8a97e",
    github: "https://github.com/aaaranas",
    live: "https://myle-photography.vercel.app/",
  },
];

export const skills = {
  Frontend: [
    "React",
    "Next.js",
    "TypeScript",
    "JavaScript",
    "Tailwind CSS",
    "HTML",
    "CSS",
    "Responsive Design",
    "Socket.io Client",
    "Flutter",
  ],
  "Backend & APIs": [
    "Node.js",
    "Express.js",
    "PostgreSQL",
    "Firebase",
    "Firestore",
    "Supabase",
    "tRPC",
    "Socket.io Server",
    "Prisma ORM",
  ],
  Tools: ["Git", "GitHub", "GitLab", "Vercel", "JetAdmin", "Docker", "Postman"],
};

export const experience = [
  {
    company: "eComia",
    role: "Web Developer Intern",
    period: "2026 · Present",
    type: "internship",
    highlights: [
      "Acting as Project Manager & Frontend Developer across projects — owning both coordination and hands-on implementation",
      "Built the Event QR Admission system end-to-end: full-screen kiosk display (React + Vite) reacting to real-time Firestore writes with celebratory animated reveals",
      "Managed a multi-platform system: web display, Flutter mobile QR scanner, and JetAdmin admin panel — all wired to the same Firebase/Firestore project",
      "Collaborating on React/Next.js e-commerce systems in a professional team environment",
    ],
    project: {
      name: "Event QR Admission",
      stack: ["React", "Vite", "Tailwind CSS", "Firebase", "Firestore", "Flutter", "JetAdmin"],
      description: "Full-screen guest check-in kiosk. Role: Project Manager & Frontend Developer (Web + Mobile). QR scanned → Firestore write → celebratory animated reveal in under 20ms.",
    },
  },
];

export const education = [
  {
    school: "University of the Philippines Cebu",
    degree: "Bachelor of Science in Computer Science",
    period: "Expected: Jul 2027",
    courses: [
      "Data Structures & Algorithms",
      "Operating Systems",
      "Database Systems",
      "Software Engineering",
      "Computer Networks",
    ],
  },
  {
    school: "Philippine Science High School — Central Visayas Campus",
    degree: "Science, Technology, Engineering & Mathematics",
    period: "Graduated: May 2021",
    courses: ["With High Honors"],
  },
];
